version: "2"

services:
  keycloak_postgres:
      image: postgres:latest
      container_name: keycloak_postgres
      restart: unless-stopped
      ports:
          - "15432:15432"
      environment:
          - POSTGRES_DB=keycloak
          - POSTGRES_USER=keycloak
          - POSTGRES_PASSWORD=keycloak
          - POSTGRES_ROOT_PASSWORD=keycloak
      volumes:
        - keycloak_postgresql_volume:/var/lib/postgresql/data
  keycloak:
      image: jboss/keycloak
      container_name: keycloak_server
      restart: unless-stopped
      environment:
        - POSTGRES_DATABASE=keycloak
        - POSTGRES_USER=keycloak
        - POSTGRES_PASSWORD=keycloak
        - PROXY_ADDRESS_FORWARDING=true
        - KEYCLOAK_USER=admin
        - KEYCLOAK_PASSWORD=admin
        - POSTGRES_PORT_5432_TCP_ADDR=postgres
        - POSTGRES_PORT_5432_TCP_PORT=5432
      links:
        - keycloak_postgres:postgres
      ports:
        - "8080:8080"
      volumes:
        - keycloak_volume:/data

volumes:
  keycloak_volume:
    external: true
  keycloak_postgresql_volume:
    external: true
