version: "2"

services:
  postgres:
      image: postgres:latest
      container_name: keycloak_postgres
      ports:
        - "15432:15432"
      environment:
          - POSTGRES_DB=keycloak
          - POSTGRES_USER=keycloak
          - POSTGRES_PASSWORD=keycloak
          - POSTGRES_ROOT_PASSWORD=keycloak
      volumes:
        - keycloak_postgresql_volume:/var/lib/postgresql
        - keycloak_postgresql_data_volume:/var/lib/postgresql/data
  keycloak:
      image: jboss/keycloak-postgres
      container_name: keycloak_server
      environment:
        - KEYCLOAK_LOGLEVEL=DEBUG
        - POSTGRES_USER=keycloak
        - POSTGRES_DATABASE=keycloak
        - POSTGRES_PASSWORD=keycloak
        - POSTGRES_PORT_5432_TCP_ADDR=postgres
        - POSTGRES_PORT_5432_TCP_PORT=5432
        - KEYCLOAK_USER=admin
        - KEYCLOAK_PASSWORD=admin
      links:
        - postgres:postgres
      ports:
        - "18443:8443"
        - "18080:8080"
      volumes:
        - keycloak_volume:/data

volumes:
  keycloak_volume:
    external: true
  keycloak_postgresql_volume:
    external: true
  keycloak_postgresql_data_volume:
      external: true